name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: setup protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - name: generate
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@ad51f572fd270f2323e3aa2c1d2775cab9087af2
          go install github.com/envoyproxy/protoc-gen-validate@v0.6.1
          go install github.com/google/wire/cmd/wire@v0.5.0
          go install github.com/swaggo/swag/cmd/swag@v1.8.4
          go mod download
          go generate ./internal/...
          go generate ./...
        env:
          GOPATH: /home/runner/go
          PATH: "$PATH:$GOPATH/bin"
      - name: build
        run: go build -v ./...
      - name: test
        run: go test -v ./...
